### PR TITLE
Parse emojis aliases dynamically

### PR DESCRIPTION
**Pull request by enzoferey**
Following up conversation at https://github.com/tommoor/react-emoji-render/pull/35.

I'm not sure what you had in mind @tommoor about how to do this (there are actually many ways), but I think this solution is pretty flexible and easy enough to understand.

Let me know what you think !

### CODE REVIEW

**Comment by tommoor** [comment]
Wow, amazing how many are missing. I think you've got the right idea but why go to the trouble of parsing the html table –  isn't the data in the json files the same?

https://raw.githubusercontent.com/iamcal/emoji-data/master/emoji_pretty.json

We could even just have node download that json file in the script rather than expecting it to be in the data directory.

**Comment by enzoferey** [comment]
>  I think you've got the right idea but why go to the trouble of parsing the html table – isn't the data in the json files the same?

In the json file you can only find the codepoints value, from which you could get the emoji eventually, but I'm not aware of any ways to get the final looking emoji to a JS file (which is much easier to manipulate later on). Using the html table we can directly copy the emoji character and that's it.

> We could even just have node download that json file in the script rather than expecting it to be in the data directory.

I thought about that, and even using Puppeteer to crawl the table URL. I think it should be more reliable to have the data locally in case they change the URL or something, but I would say there is no perfect solution here neither.

**Comment by enzoferey** [comment]
Any updates @tommoor ?

**Comment by tommoor** [comment]
Solid answers – I'm not going to nitpick this, more important that we get these new emoji's supported finally 🙌

**Comment by tommoor** [comment]
I published as `1.0.0` now we're fully upto date with the spec. Also because it seems some of the skin tones were incorrect before, so updating to this version of the lib might result in visual changes.

**Comment by enzoferey** [comment]
Great ! Thanks for making this happen and let's keep the world filled of emojis 💯 🚀 💅

**Pull request merged**
