### PR TITLE
fix: firefox doesn't support lookbehind

### PR DESCRIPTION
**Pull request by obfusk**
I keep forgetting Firefox has terrible regular expression support :(

### CODE REVIEW

**Comment by Favna** [comment]
This also affects iOS Mobile Safari, and I haven't checked MacOS Safari yet but I suspect it is also affected.

**Comment by enzoferey** [comment]
@tommoor this is a patch release 🙏

**Comment by tommoor** [comment]
`v1.2.4`

**Comment by Favna** [comment]
Wow I was literally just done implementing my code using the `react-twemoji` package. Thanks for being so fast guys! Back to this lib I go!

**Comment by obfusk** [comment]
@tommoor @enzoferey Sorry for breaking things & thanks for releasing the patch quickly!

**Comment by obfusk** [comment]
Also: someone should probably update the codesandbox in the README again.

**Pull request merged**
