### PR TITLE
Adds new aliases

### PR DESCRIPTION
**Pull request by logicminds**
* money_with_face
  * skull_with_crossbones

### CODE REVIEW

**Comment by logicminds** [comment]
I wanted to add more but some of the ones like :hot_face: and :cold_face: only seem to work for twitter. 
I could add the unicode chars but wasn't sure how they would be rendered. 

https://unicode.org/emoji/charts/full-emoji-list.html#1f600

**Comment by kytwb** [comment]
Related to #6.

**Comment by austenpayan** [comment]
Any hinderances to this getting merged?

**Comment by logicminds** [comment]
Will this be merged anytime soon?

**Pull request merged**
