### PR TITLE
support of `man_singer` and `thinking` emojis

### PR DESCRIPTION
**Pull request by ShimiSun**
`man_singer` and `thinking` emojis are currently not supported.
closes: #34

### CODE REVIEW

**Comment by tommoor** [comment]
Thanks, appreciate the effort here 😄  

There are actually a fair more than this missing from the last emoji update in 2018 – I think we need to find a definitive list and just add them all in one go rather than piecemeal.

**Comment by matthewlilley** [comment]
Consider using https://github.com/iamcal/emoji-data - This's the same dataset that Emojimart uses.

**Comment by enzoferey** [comment]
Looks like the relationship between `short name - emoji` we currently use doesn't exist in the `emoji.json` file, but we could for example parse the `table.htm` file and build our `aliases.js` file from that. I can open a PR if you want @tommoor.

**Comment by tommoor** [comment]
Absolutely. It definitely needs to be mostly automated for this lib to stand a chance of continuing to be maintained otherwise we'll always be months behind

**Pull request closed without merging**
